name = "HolyLabRegistry"
uuid = "c72e0888-c1c3-11e8-0741-c1bd6f46e678"
repo = "https://github.com/HolyLab/HolyLabRegistry.git"

description = """
Holylab julia package registry where people can
register any package within lab scope.
"""

[packages]
0de75c66-c0d4-11e8-3de9-d1632eed9267 = { name = "ISVD", path = "ISVD" }
13d07ad6-c0d4-11e8-35b1-91a532e61cc8 = { name = "FactoredMatrices", path = "FactoredMatrices"}
189fa2b0-c0d4-11e8-1b41-c5eb7281c27c = { name = "ExtraMatrix", path = "ExtraMatrix"}
19baa3cf-15a9-54b0-b671-5d0d7003ae5b = { name = "VariationalOnlineStats", path = "VariationalOnlineStats"}
9cc36475-e10c-57f8-b33d-19dcb253ebc3 = { name = "BoxTrees", path = "BoxTrees"}
cd6f60fb-236b-5882-ad4f-250d5433a9a7 = { name = "TileTrees", path = "TileTrees"}
55325cc8-c0ec-11e8-2109-1f9bd277abf4 = { name = "ShotNoise", path = "ShotNoise"}
23bcbbb2-c0d4-11e8-38f2-37d4ddb111c4 = { name = "TiledFactorizations", path = "TiledFactorizations"}
2b713a72-c0d4-11e8-0e3e-e7c72182117a = { name = "MergePairwise", path = "MergePairwise"}
597c7b4e-c0ec-11e8-1347-855d2b7c9c20 = { name = "FakeCells", path = "FakeCells"}
304b7e5e-c0d4-11e8-1391-db3dfdb9ef20 = { name = "CellSegmentation", path = "CellSegmentation"}
f385d984-c960-11e8-171c-977bba6b62a4 = { name = "IntervalFastMath", path = "IntervalFastMath"}
0f17980a-d2b6-11e8-2799-edcc513b22eb = { name = "HistogramPyramids", path = "HistogramPyramids"}
768c9593-c1e5-5107-8576-9ed3f4373482 = { name = "CoordinateSplittingPTrees", path = "CoordinateSplittingPTrees"}
7ecfceec-b993-11e8-0809-a584061f8d98 = { name = "OptimizeIVQ", path = "OptimizeIVQ"}
b9709bfb-d23d-5560-8276-8c35c4b76823 = { name = "CachedInterpolations", path = "CachedInterpolations"}
46a7138f-0d70-54e1-8ada-fb8296f91f24 = { name = "CenterIndexedArrays", path = "CenterIndexedArrays"}
67712758-55e7-5c3c-8e85-dda1d7758434 = { name = "RegisterCore", path = "RegisterCore"}
d4862ba2-f42c-5aeb-af4f-96a8884a16c4 = { name = "RegisterUtilities", path = "RegisterUtilities"}
c19381b7-cf49-59d7-881c-50dfbd227eaf = { name = "RegisterDeformation", path = "RegisterDeformation"}
464fa2a9-b19c-5c59-8698-f58c971f971e = { name = "RegisterPenalty", path = "RegisterPenalty"}
3c0dd727-6833-5f5d-a1e8-c0d421935c74 = { name = "RegisterMismatch", path = "RegisterMismatch"}
73fda715-febb-5522-a0fc-086e91958f61 = { name = "RegisterHindsight", path = "RegisterHindsight"}
abb2e897-52bf-5d28-a379-6ca321e3b878 = { name = "RegisterMismatchCommon", path = "RegisterMismatchCommon"}
ee0d8d85-fa18-576c-9601-66ebb12862d9 = { name = "RegisterMismatchCuda", path = "RegisterMismatchCuda"}
36121b08-3789-5198-aff2-59a3443d9b59 = { name = "RegisterFit", path = "RegisterFit"}
b981a1b5-4587-53b0-9c3d-454c648f6f8d = { name = "RegisterOptimize", path = "RegisterOptimize"}
2da29180-479c-54ad-8515-a35e7bf22023 = { name = "BlockRegistration", path = "BlockRegistration"}
3bd9afcd-55df-531a-9b34-dc642dce7b95 = { name = "RFFT", path = "RFFT" }
f54becb8-3809-5a58-8f2d-748913078968 = { name = "TileTreesGUI", path = "TileTreesGUI" }
dae52e8d-d666-5120-a592-9e15c33b8d7a = { name = "QuadDIRECT", path = "QuadDIRECT" }
d32f3a2f-26fa-5ce0-a2ac-000c59351c13 = { name = "NeighborhoodClustering", path = "NeighborhoodClustering" }
96ae54c0-0dff-11e9-11b2-27e67f6cc5ea = { name = "UnitAliases", path = "UnitAliases" }
75ec5d3c-0ed3-11e9-24c7-e530058603ef = { name = "ImagineHardware", path = "ImagineHardware" }
a9d8408c-0fb1-11e9-0067-cb067474114e = { name = "ImagineInterface", path = "ImagineInterface" }
b89da37c-15e8-11e9-0b03-ab0995a60613 = { name = "CachedCalls", path = "CachedCalls" }
d514a27a-15fd-11e9-2877-55d10791f35b = { name = "ImagineAnalyses", path = "ImagineAnalyses" }
43b7f2cc-1a9d-11e9-093e-178b9f97357d = { name = "ImagineProcedures", path = "ImagineProcedures" }
ff578f10-1de7-11e9-075b-65d52eaf0ec5 = { name = "ImagineWorker", path = "ImagineWorker" }
28fce3f0-1dbc-11e9-10e3-e71e6ceb4e7c = { name = "Imagine", path = "Imagine" }
978d31ce-2656-11e9-22d6-b5c46a1a3d3e = { name = "RegisterWorkerShell", path = "RegisterWorkerShell" }
935ac36e-2656-11e9-1e3b-cbaa636797af = { name = "RegisterDriver", path = "RegisterDriver" }
d8fd01e4-1764-11e9-0a01-8f76bebf08d8 = { name = "CachedArrays", path = "CachedArrays" }
26d16474-33ca-11e9-0261-c59b979c6e18 = { name = "ZWarpedArrays", path = "ZWarpedArrays" }
ac24ea0c-1830-11e9-18d4-81f172323054 = { name = "RegisterQD", path = "RegisterQD" }
35e57d1e-36d7-11e9-1ca9-f74434b2bc55 = { name = "InterleavedImages", path = "InterleavedImages" }
a0a6461a-57d1-11e9-363b-71a271cc5699 = { name = "RegisterWorkerApertures", path = "RegisterWorkerApertures" }
